# Java Gradle CircleCI 2.0 configuration file
#
# https://circleci.com/docs/2.0/language-java/ for more details

version: 2.1

general:
  artifacts:
  - /home/circleci/repo/app/build/outputs/apk/

jobs:
  build:
    docker:
    - image: circleci/android:api-28 # documented at https://circleci.com/docs/2.0/circleci-images/

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - deploy:
          command: |
            cp ./home/app/build/outputs/apk/app-release.apk ${CIRCLE_ARTIFACTS}/checkit-debug-${CIRCLE_BUILD_NUM}-${CIRCLE_SHA1}.apk

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

    #      - run:
    #          name: Run Tests
    #          command: ./gradlew lint test

      - store_artifacts:
          path: app/build/reports
          destination: reports

      - store_test_results:
          path: app/build/test-results

#  deployment:
#    beta:
#      branch: master
#      commands:
#      - cd scripts && ./build.sh
